apiVersion: v1
kind: Service
metadata:
  name: gnn-service
  labels:
    app: gnn-application
spec:
  selector:
    app: gnn-application
  type: NodePort
  ports:
    - nodePort: 31000
      ports: 80
      targetport: 3000
